LOOKBACK_YEARS = 5
TRADING_DAYS_PER_YEAR = 252
DT = 1 / TRADING_DAYS_PER_YEAR

JUMP_THRESHOLD_STD = 3.0
HESTON_ROLLING_WINDOW = 20

HORIZON_DAYS = 10
N_SIMULATION_PATHS = 10_000
N_SIMULATION_SEEDS = 20

VAR_CONFIDENCE_LEVELS = [0.95, 0.99]

KELLY_FRACTION = 0.5
KELLY_MAX_F = 1.0

HOLDINGS_PATH = "holdings.json"
CANDIDATES_PATH = "candidates.json"
PRICE_CACHE_DIR = "state/prices"
PARAMS_CACHE_PATH = "state/calibrated_params.json"
